server:
  port: 10880
dubbo:
  application:
    name: tanhua-server
  registry:
    address: zookeeper://192.168.136.160:2181
  consumer:
    check: false
# log
logging:
  level:
    root: info
    com:
      tanhua: debug
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %msg - %logger{15}%n\'
tanhua:
  sms:
    validateCodeTemplateCode: SMS_189616640
    signName: 黑马程序员
    parameterName: code
    accessKeyId: ****
    accessKeySecret: ****
  redisValidateCodeKeyPrefix: VALIDATECODE_
  secret: 76bd425b6f29f7fcc2e0bfc286043df1
  uid: TOKEN_
  oss:
    endpoint: http://oss-cn-shenzhen.aliyuncs.com
    bucketName: sxytanhua113
    url: https://sxytanhua113.oss-cn-shenzhen.aliyuncs.com
    accessKeyId: ****
    accessKeySecret: ****
  face:
      appId: 24437578
      apiKey: ****
      secretKey: ****
  # ===================================================================
  # 分布式文件系统FDFS配置
  # ===================================================================
fdfs:
    so-timeout: 1500
    connect-timeout: 600
    #缩略图生成参数
    thumb-image:
      width: 150
      height: 150
    #TrackerList参数,支持多个
    tracker-list: 192.168.136.160:22122
    web-server-url: http://192.168.136.160:8888/
spring:
  redis:
    host: 192.168.136.160
    port: 6379
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
